apiVersion: v1
kind: Service
metadata:
  name: hmdp-fe #TODO: to specify your service name
  labels:
    app: hmdp-fe
spec:
  selector:
    app: hmdp-fe #TODO: change label selector to match your backend pod
  ports:
  - protocol: TCP
    name: http
    port: 80 #TODO: choose an unique port on each node to avoid port conflict
    targetPort: 80
  type: NodePort
#  type: LoadBalancer